# Generated by Django 5.0.6 on 2024-06-22 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('cpf', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abastecimentos', models.CharField(max_length=50)),
                ('tanque', models.CharField(max_length=50)),
                ('bomba', models.CharField(max_length=50)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerentes.gerente')),
            ],
        ),
    ]
