# Generated by Django 5.0.6 on 2024-06-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abastecimentos',
            old_name='Abastecimentos',
            new_name='abastecimento',
        ),
    ]
