# Generated by Django 5.0.6 on 2024-06-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerentes', '0002_rename_abastecimentos_abastecimentos_abastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentos',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='abastecimentos',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abastecimentos',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
