# Generated by Django 5.0.6 on 2024-06-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerentes', '0003_abastecimentos_quantidade_abastecimentos_valor_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abastecimentos',
            old_name='valor_unitario',
            new_name='valor',
        ),
    ]
