# Generated by Django 5.0.6 on 2024-06-24 00:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerentes', '0004_rename_valor_unitario_abastecimentos_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abastecimento', models.CharField(max_length=50)),
                ('tanque', models.CharField(max_length=50)),
                ('bomba', models.CharField(max_length=50)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerentes.gerente')),
            ],
        ),
        migrations.DeleteModel(
            name='Abastecimentos',
        ),
    ]
