# Generated by Django 5.0.6 on 2024-07-09 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerentes', '0005_abastecimento_delete_abastecimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='data_abastecimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
